### ISSUE TITLE
Add platformio library.json file

### ISSUE THREAD

**Issue by karrots** [LowPowerLab/WirelessProgramming#2]
It would be nice to have these libraries registered with [platformio.org](http://platformio.org) for easy install similar to some of your other libraries.

**Comment by LowPowerLab** [comment]
Excellent suggestion, I see my Moteino and MoteinoMEGA are already registered on Platformio, I was unaware. I will look into this as time permits, thanks!

**Comment by LowPowerLab** [comment]
OK I added the library.json file, not sure what the next step is... will they crawl and pick it up? Or do I have to register it?

**Comment by karrots** [comment]
Unsure exactly. Just started using it this week when I wanted to setup some CI stuff. I think there is a register CLI command you run. I figured you'd know as most of the other libraries had such files.

**Comment by karrots** [comment]
http://docs.platformio.org/en/latest/userguide/lib/cmd_register.html#cmd-lib-register

**Comment by LowPowerLab** [comment]
You'd be surprised how much I don't know :baby:

**Comment by LowPowerLab** [comment]
I tried the register command
platformio lib register https://github.com/LowPowerLab/WirelessProgramming/blob/master/library.json
I get this:
Invalid library config: https://github.com/LowPowerLab/WirelessProgramming/blob/master/library.json

I then tried: platformio lib register https://raw.githubusercontent.com/LowPowerLab/WirelessProgramming/master/library.json

I get this: Invalid library config: The library is already registered
Searching on Platformio doesn't find it so not sure what's next...

**Comment by karrots** [comment]
I get the impression from looking at the gitrepo for platformio that the process isn't very automated for the initial setup.

BTW I submitted this bug platformio/platformio#335

**Comment by karrots** [comment]
I see why you were unaware of the `library.json` it looks like the platformio author submitted a PR for the file in your other libraries. 

lowpowerlab/SPIFlash#6

**Comment by LowPowerLab** [comment]
Yup I merged them thinking they can't be a bad thing but I was not familiar with platformio.
So we are keeping this issue open until we find a way to register the lib or it gets picked up?

**Comment by karrots** [comment]
No go ahead and close it. If the register command said its been submitted already we can just wait.

**Comment by LowPowerLab** [comment]
Cool, thanks!
