### ISSUE TITLE
WireLessProgramming.exe is crashing during upload

### ISSUE THREAD

**Issue by MrLight** [LowPowerLab/WirelessProgramming#3]
HI,
the WireLessProgramming.exe is crashing during uploading a new sketch.
I get a StringToNumber FormatException after the first package is uploaded to the monteino. Same upload with the python client is working well...

```System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   bei WirelessProgramming.Form1.waitForSEQ(SerialPort ser, Int32 seq)
   bei WirelessProgramming.Form1.doTransmission()```

the Output is:
```
Opening COM5 @ 115200baud ...
SET TARGET: TO:123FAIL: target set error, exiting...
Opening COM1 @ 115200baud ...
SET TARGET: TO:123
Moteino: [TO:123:OK]
TARGET SET OK
FLX?
FLX?
Moteino: [FLX?OK]
HANDSHAKE OK!
TX > FLX:0:100000000C9463000C948E0F0C94BB0F0C948B001B
Moteino: RFTX > 464c583a303a0c9463000c948e0f0c94bb0f0c948b00
```

**Comment by LowPowerLab** [comment]
Thanks, I got this reported here as well: https://lowpowerlab.com/forum/index.php/topic,1506.0/topicseen.html
Will look into asap.

**Comment by LowPowerLab** [comment]
Can you please try the latest exe and see if it solves your issue?

**Comment by MrLight** [comment]
Problem is solved!
THANX!
